### ISSUE TITLE
能否将找不到字典数据时的异常处理交给用户决定

### ISSUE THREAD

**Issue by YaoaY** [EasyAbp/Abp.DataDictionary#12]
`CacheDataDictionaryValueProvider` 在找不到字典数据时直接抛出了404
但个人感觉其实这种情况下，直接返回null，不渲染或者fallback就行了。

能否根据用户的配置进行异常处理？

https://github.com/EasyAbp/Abp.DataDictionary/blob/5d2a5e9bf81071839d6e68199ccc2725dd16f4e1/src/EasyAbp.Abp.DataDictionary.Domain/RuleValueProviders/CacheDataDictionaryValueProvider.cs#L41

**Comment by real-zony** [comment]
See (https://github.com/EasyAbp/Abp.DataDictionary/pull/20).
