### ISSUE TITLE
Data dictionary purpose

### ISSUE THREAD

**Issue by jtasko** [EasyAbp/Abp.DataDictionary#2]
Hi

Can you tell me more about the intent of the data dictionary module? 

Will it be possible to use it to document the domain layer, or is it to document the data transfer objects?

Or, am I missing the point.

Thanks
Jamie

**Comment by GameBelial** [comment]
Hi jtasko,
Sorry to reply to you so late.
The data dictionary is used to store dynamically changing attributes. For example, there is a gender dictionary, which may be composed of males and females in the first version.
We have a Person entity, which has a Sex attribute to store the gender of the person, and where we store the dictionary value Code.
In the new version, we need to add LGBT, just add a new dictionary value to the gender dictionary, without changing the code.

**Comment by jtasko** [comment]
@GameBelial, thanks for the info.
